from azad.exp.alternatives.wythoff_dqn1 import wythoff_dqn1
from azad.exp.alternatives.wythoff_dqn2 import wythoff_dqn2
from azad.exp.alternatives.wythoff_dqn3 import wythoff_dqn3
from azad.exp.alternatives.wythoff_dqn4 import wythoff_dqn4
from azad.exp.alternatives.optuna_dqn2 import optuna_dqn2
from azad.exp.alternatives.wythoff_dqn3 import evaluate_dqn2
from azad.exp.alternatives.wythoff_dqn3 import evaluate_dqn3
from azad.exp.alternatives.wythoff_mcts import wythoff_mcts
from azad.exp.alternatives.wythoff_alphazero import wythoff_alphazero
